#convert UFO dump text to scenario.xml
#Author: Rudolf

#usage:
    #copy the UFO dump output to a .txt file (see objDump.txt for example)
    #python3 path/to/dumpToAI.py path/to/objDump.txt > output.xml

import xml.etree.ElementTree as ET
import sys

inp = open(sys.argv[1], "r").readlines()
desc = "This scenario was automagicaly generated by Rudolf's script"
il = 0
n = 0
d = "double"

def pe(tag, txt, t=""):
    if t == "":
        print('\t'*il + "<" + tag + ">" + txt + "</" + tag + ">")
    else:
        print('\t'*il + "<" + tag + ' type="' + t + '">' + txt + "</" + tag + ">")

print('<?xml version="1.0"?>')
print()
print("<PropertyList>")
print("\t<scenario>")
print("\t\t<name>test</name>")

il=3
for l in inp:
    e = l.split(" ")
    m = e[1]
    lat = e[3]
    lon = e[2]
    alt = e[4]
    hdg = e[5]
    
    print("\t\t<entry>")
    pe("type", "ship")
    pe("model", m)
    pe("name", "object"+str(n))
    pe("latitude", lat, d)
    pe("longitude", lon, d)
    pe("speed", "0", d)
    pe("rudder", "0", d)
    pe("heading", hdg, d)
    pe("altitude", alt, d)
    print("\t\t</entry>")

print("\t</scenario>")
print("</PropertyList>")
